### ISSUE TITLE
Unknown button type ‘show-pair’

### ISSUE THREAD

**Issue by lispnik** [joaotavora/sly#114] opened 2017-04-09 17:27 UTC
I'm not sure if this is a smartparens thing or a sly thing. I'm using smartparens with sly and if `show-smartparens-mode` is enabled, then the following error occurs. Disabling `show-smartparens-mode` fixes the problem. As a work around, I just enable `show-paren-mode` (the one that comes with emacs) instead of `show-smartparens-mode`.

```
Debugger entered--Lisp error: (error "Unknown button type ‘show-pair’")
  signal(error ("Unknown button type ‘show-pair’"))
  error("Unknown button type `%s'" show-pair)
  button-type-get(show-pair supertype)
  button-type-subtype-p(show-pair sly-button)
  #[(button) "\302\303\304\")\305\"\205	?\206	!\207" [button filter button-type-subtype-p button-get type sly-button] 4](#<overlay from 627 to 628 in pong.lisp>)
  cl-remove(nil (#<overlay from 655 to 656 in pong.lisp> #<overlay from 627 to 628 in pong.lisp>) :if-not #[(button) "\302\303\304\")\305\"\205	?\206	!\207" [button filter button-type-subtype-p button-get type sly-button] 4])
  apply(cl-remove nil (#<overlay from 655 to 656 in pong.lisp> #<overlay from 627 to 628 in pong.lisp>) :if-not #[(button) "\302\303\304\")\305\"\205	?\206	!\207" [button filter button-type-subtype-p button-get type sly-button] 4] nil)
  cl-remove-if-not(#[(button) "\302\303\304\")\305\"\205	?\206	!\207" [button filter button-type-subtype-p button-get type sly-button] 4] (#<overlay from 655 to 656 in pong.lisp> #<overlay from 627 to 628 in pong.lisp>))
  sly-button--overlays-in(627 657 sly-stickers--sticker-id)
  sly-button--overlays-between(627 657 sly-stickers--sticker-id)
  sly-stickers--stickers-between(627 657)
  sly-stickers--compile-region-aware-of-stickers-1(627 657 #[514 "\211\211\203\211A\262\242\202\300\301\302GD\"\211A\262\242\203*\300\301\302\303G\\D\"\210\211\2044\304\305\"\210\306\302\203D\307\310	G\"\202E\311#\207" [signal wrong-number-of-arguments nil 2 mapc sly-stickers--disarm-sticker sly-compilation-finished format " (%d stickers armed)" " (stickers failed to stick)"] 11 "\n\n(fn STICKERS RESULT-AND-STUCK-P)"] :fallback t :flash t)
  sly-stickers-compile-region-aware-of-stickers(627 657)
  sly-compile-region(627 657)
  apply(sly-compile-region (627 657))
  sly-compile-defun(nil)
  funcall-interactively(sly-compile-defun nil)
  #<subr call-interactively>(sly-compile-defun nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> sly-compile-defun nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (sly-compile-defun nil nil))
  call-interactively(sly-compile-defun nil nil)
  command-execute(sly-compile-defun)
``

**Comment by joaotavora** [comment] 2017-04-09 22:47
Seems to be a duplicate of #34. Closing in favor of that issue, which I just reopened. Perhaps you can add a better reproduction recipe there. I will look into this when I can (unfortunately might not be very very soon). 

Meanwhile, at the risk of being intrusive to your personal taste, might I suggest you try out Emacs's own `electric-pair-mode` which I personally find vastly superior to smartparens (and that opinion has nothing to do with the fact that I wrote it :-)

**Comment by lispnik** [comment] 2017-04-10 16:42
Cool. I will try out `electric-pair-mode`! I added a MWE to the other ticket.

**Closed** 2017-04-10 22:44 UTC
