### ISSUE TITLE
SLY repl closes when choosing last restart on errors

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#265] opened 2019-10-14 10:56 UTC
Recipe:

- M-x sly
- (setf foo bar)
- In the debug buffer, choose the last restart, typically

```
 5: [ABORT] abort thread (#<THREAD "sly-channel-2-mrepl-remote-2" RUNNING {100315CAE3}>)
```

Result in the REPL:

```
Process sly-pty-4-2 killed

; Server side close
; --------------------------------------------------------
```

The buffer becomes unusable.  Killing the buffer calling `sly` works.

**Comment by Ambrevar** [comment] 2019-10-14 10:56
SLIME does not seem to have this problem.

**Comment by joaotavora** [comment] 2019-10-14 11:02
This is a duplicate of #122. There were many attempts to fix this problem, but none of them were workable.  

> SLIME does not seem to have this problem.

SLIME only has one REPL.

**Closed by joaotavora** 2019-10-14 11:02 UTC

**Comment by Ambrevar** [comment] 2019-10-14 11:26
SLIME also has "mrepl", but I haven't tried to reproduce the issue with it.

**Comment by joaotavora** [comment] 2019-10-14 11:43
@Ambrevar 99% sure the SLIME "mrepl" contrib will have the same problem, since `sly-mrepl` is a heavily rewritten version of it.

That said, the problem is not completely unsolvable.  If it bothers you very much, I can look into it again.  Perhaps somehow "hiding" the "dangerous" restart for novice users is the way to go.

**Comment by junkicide** [comment] 2021-08-23 12:11
I'm currently facing this issue. Any workarounds?

**Comment by philippludwig** [comment] 2025-02-18 09:02
> [@Ambrevar](https://github.com/Ambrevar) 99% sure the SLIME "mrepl" contrib will have the same problem, since `sly-mrepl` is a heavily rewritten version of it.
> 
> That said, the problem is not completely unsolvable. If it bothers you very much, I can look into it again. Perhaps somehow "hiding" the "dangerous" restart for novice users is the way to go.

Any updates on this? Coming from SLIME, I have accidentally killed my session several times now.

**Comment by joaotavora** [comment] 2025-02-18 18:53
If you kill your REPL session, you can just start a new one.  This obviously does not kill the lisp session. That said, how are you invoking this restart?  Simply pressing 5?  it won't be the 5th restart every time, right? What it the list of restarts you are typical seeing and how are you invoking it?  

I haven't looked at SLY or Common Lisp in a while, but I'm modestly sure the restart is coming from the implementation. So I wouldn't know how to hide it in CL (at least not with usual restart visibility functions).  OTOH, hiding it in Elisp would be hideous. 
There are other possible solutions, like in `slynk:invoke-nth-restart`, but to do them in a non-fugly fashion would require some hooks so that the `slynk-mrepl.lisp` can somehow protect that restart with an interactive prompt.  But even that would be ugly.  Not to mention I have 0 time to hack on that now.

So that's why I'm trying to understand why you are bumping into this.  For example, I think I just typed `q` when I wanted to abort (I have `q` bound to `sly-db-abort`).  It picks the first "ABORT" restart and that's usually what I want. It's pretty much in line the usual Emacs idiom that `q` after a popup brings you back to the state you were in.

**Comment by philippludwig** [comment] 2025-02-19 07:58
> If you kill your REPL session, you can just start a new one. 
Yes, but i need to re-eval everything, which is pretty annoying.

> What it the list of restarts you are typical seeing and how are you invoking it?
e.g.:
```
Execution of a form compiled with errors.
Form:
  (2)
Compile-time error:
  illegal function call
   [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT] abort thread (#<THREAD tid=1635111 "sly-channel-1-mrepl-remote-1" RUNNING {100228FA53}>)
```
I press `2` by muscle memory and that kills the whole session, because in SLIME, it looks like this:

```
Execution of a form compiled with errors.
Form:
  (2)
Compile-time error:
  illegal function call
   [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Exit debugger, returning to top level.
```
Pressing `2` just gets you out of the debugger, without killing the session.

It is good to know that `q` exists; I will try to get used to it.

**Comment by aadcg** [comment] 2025-02-19 09:37
@philippludwig which CL implementations did you use to test? Only SBCL?

**Comment by joaotavora** [comment] 2025-02-19 09:39
> I press 2 by muscle memory 

Right.  Hmmm, but surely you've noticed if you do something else then calling a function illegally, like the simplest mistake of mistyping a symbol, then you get these restarts:

```
The variable ASD is unbound.
   [Condition of type UNBOUND-VARIABLE]

Restarts:
 0: [CONTINUE] Retry using ASD.
 1: [USE-VALUE] Use specified value.
 2: [STORE-VALUE] Set specified value and use it.
 3: [RETRY] Retry SLY mREPL evaluation request.
 4: [*ABORT] Return to SLY's top level.
 5: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004468003}>)
```

And restart number `2` isn't the abort at all.  Similarly, if you switch implementations, the number of restarts will change.  Sometimes the restart list is extremely long, depending on what you're trying to do.  `q` always chooses the "first abort restart" and that's why it's useful.

So, upon analysis, I think this issue ought to stay closed.

**Comment by philippludwig** [comment] 2025-02-19 12:17
> [@philippludwig](https://github.com/philippludwig) which CL implementations did you use to test? Only SBCL?

Yes.

> So, upon analysis, I think this issue ought to stay closed.

I see. But is there a reason that sly offers this "kill everything" option, while SLIME does not?

Maybe I will just hack something together for my personal use case, where it removes all Restarts that contain the word "thread".

**Comment by aadcg** [comment] 2025-02-19 19:43
I use SLY daily and this is a non-issue IMO. As mentioned, `q` usually does what you want.
