### ISSUE TITLE
SBCL crash on Sly repl interrupt

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#133] opened 2017-11-10 00:38 UTC
When sitting at the sly repl and pressing C-c C-c to interrupt, I seem to hit an infinite loop of nested errors, and eventually SBCL gets killed by the OS.

Here's the trace from inferior-lisp:

```
SLYNK's ASDF loader finished.
62878
* WARNING: redefining SLYNK::SYMBOL-INDENTATION in DEFUN
WARNING: redefining SLYNK::MACRO-INDENTATION in DEFUN
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}>
0: ((FLET #:CLEANUP-FUN-691 :IN SB-THREAD::%CONDITION-WAIT)) [cleanup]
1: (SB-THREAD:CONDITION-WAIT #<SB-THREAD:WAITQUEUE  {1004028443}> #<SB-THREAD:MUTEX owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> {1004028413}> :TIMEOUT NIL)
2: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SLYNK-BACKEND:RECEIVE-IF) {5CCEE8B}> #<SB-THREAD:MUTEX owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> {1004028413}> NIL T NIL)
4: ((FLET SLYNK-BACKEND:RECEIVE-IF :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20171108.1437/slynk/backend/sbcl.lisp") #<CLOSURE (LAMBDA (SLYNK::E) :IN SLYNK::WAIT-FOR-EVENT) {1004028A6B}> NIL)
5: (SLYNK::WAIT-FOR-EVENT (OR (:EMACS-REX . SLYNK::_) (:EMACS-CHANNEL-SEND . SLYNK::_)) NIL)
6: (SLYNK::PROCESS-REQUESTS NIL)
7: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
8: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
9: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {100402800B}>)
10: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20171108.1437/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {100402800B}>)
11: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
12: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (*) (**) (***) (/) (//) (///) (+) (++) (+++) (SLYNK-MREPL::*HISTORY* . #()) (*STANDARD-OUTPUT* . #<SB-SYS:FD-STREAM for "socket 127.0.0.1:62880, peer: 127.0.0.1:62881" {1003C1D433}>) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {100402804B}>)
13: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
14: ((FLET #:WITHOUT-INTERRUPTS-BODY-1138 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
15: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
16: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
17: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {5CCFB4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}>> NIL T NIL)
18: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1004020FCB}> (#<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> #<SB-THREAD:THREAD "slynk-indentation-cache-thread" RUNNING {1005CB81D3}> #<SB-THREAD:THREAD "reader-thread" RUNNING {1005CB8083}> #<SB-THREAD:THREAD "control-thread" RUNNING {1005CB4A33}> #<SB-THREAD:THREAD "Slynk Sentinel" RUNNING {1005A18193}> #<SB-THREAD:THREAD "main thread" RUNNING {1002DBAD23}>) NIL NIL NIL NIL)
19: ("foreign function: #x4338BC")
20: ("foreign function: #x403751")
21: ("foreign function: #x4501E0")
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}>
0: ((FLET #:CLEANUP-FUN-691 :IN SB-THREAD::%CONDITION-WAIT)) [cleanup]
1: (SB-THREAD:CONDITION-WAIT #<SB-THREAD:WAITQUEUE  {1004028443}> #<SB-THREAD:MUTEX owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> {1004028413}> :TIMEOUT NIL)
2: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SLYNK-BACKEND:RECEIVE-IF) {5CCEE8B}> #<SB-THREAD:MUTEX owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> {1004028413}> NIL T NIL)
4: ((FLET SLYNK-BACKEND:RECEIVE-IF :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20171108.1437/slynk/backend/sbcl.lisp") #<CLOSURE (LAMBDA (SLYNK::E) :IN SLYNK::WAIT-FOR-EVENT) {1004028A6B}> NIL)
5: (SLYNK::WAIT-FOR-EVENT (OR (:EMACS-REX . SLYNK::_) (:EMACS-CHANNEL-SEND . SLYNK::_)) NIL)
6: (SLYNK::PROCESS-REQUESTS NIL)
7: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
8: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
9: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {100402800B}>)
10: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20171108.1437/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {100402800B}>)
11: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
12: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (*) (**) (***) (/) (//) (///) (+) (++) (+++) (SLYNK-MREPL::*HISTORY* . #()) (*STANDARD-OUTPUT* . #<SB-SYS:FD-STREAM for "socket 127.0.0.1:62880, peer: 127.0.0.1:62881" {1003C1D433}>) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {100402804B}>)
13: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
14: ((FLET #:WITHOUT-INTERRUPTS-BODY-1138 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
15: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
16: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
17: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {5CCFB4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}>> NIL T NIL)
18: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1004020FCB}> (#<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004021A53}> #<SB-THREAD:THREAD "slynk-indentation-cache-thread" RUNNING {1005CB81D3}> #<SB-THREAD:THREAD "reader-thread" RUNNING {1005CB8083}> #<SB-THREAD:THREAD "control-thread" RUNNING {1005CB4A33}> #<SB-THREAD:THREAD "Slynk Sentinel" RUNNING {1005A18193}> #<SB-THREAD:THREAD "main thread" RUNNING {1002DBAD23}>) NIL NIL NIL NIL)
19: ("foreign function: #x4338BC")
20: ("foreign function: #x403751")
21: ("foreign function: #x4501E0")
```
It just keeps on repeating like that.

Note that if I interrupt during an eval, things seem to be fine
that is, if I issue something like

```lisp
(dotimes (i 1000000000000))
```
then C-c C-c while it's evaluating, I get a proper debugger pop-up as expected. It seems to only cause an issue when interrupting at an idle repl.

My setup:
* Sly 20171011.809
* Emacs 25.0.90.3 AMD64
* SBCL 1.3.18 AMD64
* Windows 10 AMD64

This had come up in #132 but I assumed it was part of/related to it

**Comment by joaotavora** [comment] 2017-11-10 04:38
> This had come up in #132 but I assumed it was part of/related to it

Yes, this is a different bug, but I can't reproduce it. 

I wonder if you can also post a backtrace for your "healthy" case (i.e. the `dotimes` thing for example)

Anyway, I suspect this is related to windows and will have to find some virtual machine to test this in, which might take a little while longer.

Also, I wonder if you could possibly test this against a very recent SBCL (that's a bit difficult to do maybe because you would have to compile it, or find binaries for it)

Also, I wonder If you could test this against a SLY version just *before* commit ddd824a67d85795111a7bbf69e42a46540cdbb11. You'd have to rewind to ddd824a67d85795111a7bbf69e42a46540cdbb11^1 and hope that ASDF does the right thing and recompiles the lisp into new fasls (it should though).

Then I think it would be useful if you could trace these two functions.
```
(trace slynk::interrupt-worker-thread slynk::invoke-or-queue-interrupt)
```
Normally, I would ask you to do this with SLY's trace dialog, but since your `C-c C-c` is crashing SBCL that wouldn't be much use. I fear that even in this case we might never really see the output of the traces.

Finally, FTR, here's what I consider a "normal" backtrace in SBCL 1.3.21.

```
  0: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGING-ENVIRONMENT :IN "/home/capitaomorte/Source/Emacs/sly/slynk/backend/sbcl.lisp") #<FUNCTION (LAMBDA NIL :IN SLYNK::DEBUG-IN-EMACS) {22864BDB}>)
  1: (SLYNK::DEBUG-IN-EMACS #<SIMPLE-ERROR "Interrupt from Emacs" {1001DF1633}>)
  2: (SLYNK:INVOKE-SLY-DEBUGGER #<SIMPLE-ERROR "Interrupt from Emacs" {1001DF1633}>)
  3: (SLYNK:SIMPLE-BREAK "Interrupt from Emacs")
  4: (SLYNK-BACKEND:CHECK-SLY-INTERRUPTS)
  5: ((FLET SLYNK-BACKEND:RECEIVE-IF :IN "/home/capitaomorte/Source/Emacs/sly/slynk/backend/sbcl.lisp") #<CLOSURE (LAMBDA (SLYNK::E) :IN SLYNK::WAIT-FOR-EVENT) {1001DF09AB}> NIL)
  6: (SLYNK::WAIT-FOR-EVENT (OR (:EMACS-REX . SLYNK::_) (:EMACS-CHANNEL-SEND . SLYNK::_)) NIL)
  7: (SLYNK::PROCESS-REQUESTS NIL)
  8: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
  9: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 10: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1001DF000B}>)
 11: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/capitaomorte/Source/Emacs/sly/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THR..
 12: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
 13: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (*) (**) (***) (/) (//) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {1001DF004B}>)
 14: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 16: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 17: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 18: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF524ECDB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 19: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1001DEBB73}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1001DEB12B}> (#<SB-TH..
 20: ("foreign function: call_into_lisp")
 21: ("foreign function: new_thread_trampoline")
```

**Comment by Zulu-Inuoe** [comment] 2017-11-10 06:26
I've got a built version of SBCL 1.4.1 (+ a couple of commits since the official 1.4.1 doesn't build on Windows).
Sly has issues loading now. An error with no description relating back to this line in slynk-fancy-inspector.lisp:

```lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (slynk-require :slynk-util))
```
ASDF complains when sly tries to load that with this:

```
; caught WARNING:
;   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:LOAD-OP
;   '("slynk-util")) while visiting
;   (ASDF/LISP-ACTION:COMPILE-OP "slynk-fancy-inspector"
;    "../contrib/slynk-fancy-inspector")
;   - please use proper dependencies instead
```

My guess is that the new SBCL version has some new ASDF. I noticed some new ASDF warnings about other things, as well. I was able to comment out that line and have sly load up fine, so ¯\_(ツ)_/¯
I'm now seeing intermittent behavior with the interrupts, where one may work, and the next either crashes sbcl or puts sly in a weird state.
Tomorrow I'll look at this more in-depth to try and figure out what's going on. Likely revert my SBCL to 1.3.21 if that builds. I completely agree that it's likely to be a Windows related issue. My guess is with either signal handling or wait functions (or both) since threading dynamics differ from Linux platforms.

Thanks!

**Comment by joaotavora** [comment] 2017-11-10 09:06
Wilfredo Velázquez-Rodríguez <notifications@github.com> writes:

> I've got a built version of SBCL 1.4.1 (+ a couple of commits since
> the official 1.4.1 doesn't build on Windows).  Sly has issues loading
> now.

Yeah this is issue #134. It should be easy enough to fix.

>An error with no description relating back to this line in
> slynk-fancy-inspector.lisp:
>
> (eval-when (:compile-toplevel :load-toplevel :execute)
>   (slynk-require :slynk-util))
>
> ASDF complains when sly tries to load that with this:
>
> ; caught WARNING:
> ;   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:LOAD-OP
> ;   '("slynk-util")) while visiting
> ;   (ASDF/LISP-ACTION:COMPILE-OP "slynk-fancy-inspector"
> ;    "../contrib/slynk-fancy-inspector")
> ;   - please use proper dependencies instead
>
> My guess is that the new SBCL version has some new ASDF. I noticed
> some new ASDF warnings about other things, as well. I was able to
> comment out that line and have sly load up fine, so ¯_(ツ)_/¯

No problem, that's what the person that reported #134 did also. It
should work fine.

> I'm now
> seeing intermittent behavior with the interrupts, where one may work,
> and the next either crashes sbcl or puts sly in a weird state.
> Tomorrow I'll look at this more in-depth to try and figure out what's
> going on. Likely revert my SBCL to 1.3.21 if that builds. I completely
> agree that it's likely to be a Windows related issue.

I wonder 2 things. (1) if we could build a minimal test case without SLY
that reproduces the crash. Actually *you* would have to build that since
you have the windows. (2) if SLIME would also exhibit this
behaviour. SLIME's REPL is quite different from SLY's but this
particular part (responding to interrupts) should be equivalent.

**Comment by Zulu-Inuoe** [comment] 2017-11-11 22:26
Here's the trace from the dotimes example

```
  0: ((LAMBDA ()))
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DOTIMES (I 10000000000)) #<NULL-LEXENV>)
  2: (EVAL (DOTIMES (I 10000000000)))
  3: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))
  4: (SLYNK::CALL-WITH-RETRY-RESTART "Retry SLY mREPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1) {10027B5DFB}>)
  5: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))
  6: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
  7: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (* . 1) (**) (***) (/ 1) (//) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {10027B5A6B}>)
  8: (SLYNK-MREPL::MREPL-EVAL-1 #<SLYNK-MREPL::MREPL mrepl-1-1> "(dotimes (i 10000000000))")
  9: (SLYNK-MREPL::MREPL-EVAL #<SLYNK-MREPL::MREPL mrepl-1-1> "(dotimes (i 10000000000))")
 10: (SLYNK::PROCESS-REQUESTS NIL)
 11: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 12: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 13: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {100631800B}>)
 14: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20171108.1437/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-C..
 15: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
 16: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (* . 1) (**) (***) (/ 1) (//) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {100631804B}>)
 17: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 18: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 19: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 20: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 21: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {5E1FB5B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "..
 22: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1006311543}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1006310ABB}> (#<SB-TH..
 23: ("foreign function: #x437868")
 24: ("foreign function: #x403E91")
```
Here's the trace from a the worker during that interrupt:

```
CL-USER> (dotimes (i 10000000000))
  0: (SLYNK::INTERRUPT-WORKER-THREAD
      #<SLYNK::MULTITHREADED-CONNECTION {1005770293}> 1)
  0: SLYNK::INTERRUPT-WORKER-THREAD returned NIL
  0: (SLYNK::INVOKE-OR-QUEUE-INTERRUPT #<FUNCTION SLYNK:SIMPLE-BREAK>)
```

And finally, here's the trace with the 'bad' interrupt (bare repl interrupt)
```
  0: (SLYNK::INTERRUPT-WORKER-THREAD
      #<SLYNK::MULTITHREADED-CONNECTION {1005770293}> 1)
  0: SLYNK::INTERRUPT-WORKER-THREAD returned NIL
  0: (SLYNK::INVOKE-OR-QUEUE-INTERRUPT #<FUNCTION SLYNK:SIMPLE-BREAK>)
  0: SLYNK::INVOKE-OR-QUEUE-INTERRUPT returned T
```

Honestly I'm seeing all sorts of instability with these interrupt and eval calls. Earlier I did the dotimes example and when I tried interrupting, sly was just waiting, and sbcl sat at 0% CPU.
As per SLIME, I've been using it for years and I've never seen it behave this way, so there must be a subtle difference between the code as far as that is concerned.

I'm going to continue looking at this, but I wanted to post an update.
Thanks!

**Comment by Zulu-Inuoe** [comment] 2017-11-11 22:46
I noticed that the slynk wake-thread implementation uses sb-thread:with-mutex, whereas swank used sb-thread:with-recursive-lock.
Changing it to recursive seems to fix the issue, though I haven't enough experience to know what it might break.
As per the instability, I noticed that if I during an interrupt I abort the thread (one of the restarts available), sly stops responding. That may be an issue of itself, though!
The behavior in SLIME (though I question the merits of even having it...) was that the repl thread would get replaced with another. I just ran into it because the closest 'ABORT' restart is the one I usually pick, and aborting the thread is typically the 'closest' presented.

**Comment by joaotavora** [comment] 2017-11-11 23:52
Wilfredo Velázquez-Rodríguez <notifications@github.com> writes:

> I noticed that the slynk wake-thread implementation uses sb-thread:with-mutex, whereas swank
> used sb-thread:with-recursive-lock.
> Changing it to recursive seems to fix the issue, though I haven't enough experience to know what
> it might break.

This is interesting. I mostly cherry-pick changes to the sbcl backend
from SLIME. The low-level stuff is mostly shared between SLY and
SLIME. I'll investigate and probably do the change if I find I messed up
the cherry-pick.

> As per the instability, I noticed that if I during an interrupt I abort the thread (one of the restarts
> available), sly stops responding. That may be an issue of itself, though!

Yes, this is issue #122. Sly doesn't "stop responding", though, you can
start a new repl with M-x sly-mrepl-new.

> The behavior in SLIME (though I question the merits of even having
> it...) was that the repl thread would get replaced with another. I
> just ran into it because the closest 'ABORT' restart is the one I
> usually pick, and aborting the thread is typically the 'closest'
> presented.

Yes this is explained in that issue. It has some merits, but is a low
prio for me.

**Comment by joaotavora** [comment] 2017-11-12 00:10
@Zulu-Inuoe, I believe just commited a fix. Thanks to your investigation I found that the relatively recent SLIME commit touching this code was not yet in SLY.

And I almost bet that if you rewind SLIME to somewhere between its commits ef68a0b4aaac3edc9fda94ce33d43d6ea5d04ef8 and the earlier 5f23adaa88c034449d935b7a0bc26ed936d5ed0e you will see those problems on Windows. 

I'm tentatively closing this issue, but feel free to let me know if the problems don't go away.

**Closed by joaotavora** 2017-11-12 00:10 UTC

**Comment by Zulu-Inuoe** [comment] 2017-11-12 01:27
Great! Thanks for your work, as well as the links to that other issue.
