### ISSUE TITLE
Unexpected reply

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#385] opened 2020-12-07 08:53 UTC
This started happening a few months ago, and I'm just getting around to reporting it because it is quite annoying. Every few minutes, this error is invoked, which pauses Emacs for a good 5 seconds while I am typing.

```
error in process filter: sly-dispatch-event: Unexpected reply: 1778 (:ok ("(define-hook ===> hook-type <=== (self component-type &key (optimize t)) &body body)" t))
error in process filter: Unexpected reply: 1778 (:ok ("(define-hook ===> hook-type <=== (self component-type &key (optimize t)) &body body)" t))
```

Here's another occurence in my Messages buffer:

```
-event: Unexpected reply: 904 (:ok ("(defun name ===> lambda-list <=== &body body)" t))
error in process filter: Unexpected reply: 904 (:ok ("(defun name ===> lambda-list <=== &body body)" t))
```

and another:

```
error in process filter: sly-dispatch-event: Unexpected reply: 606 (:ok (:not-available t))
error in process filter: Unexpected reply: 606 (:ok (:not-available t))
```

and another:

```
error in process filter: sly-dispatch-event: Unexpected reply: 165 (:ok (:not-available t))
error in process filter: Unexpected reply: 165 (:ok (:not-available t))
```

and one more from today:

```
error in process filter: sly-dispatch-event: Unexpected reply: 2999 (:ok (:not-available t))
error in process filter: Unexpected reply: 2999 (:ok (:not-available t))
```

**Comment by joaotavora** [comment] 2020-12-07 21:14
Yuck, this isn't good.  I see this once in a while , too, but not nearly "every few minutes".  I see it once a week at most.  It's very hard to pin down.  You can give me some help tho:

1.  Tell me how often you see this.  Is it really every few minutes?  That's very odd, but in a sense good.
2.  Since it's so easy to reproduce for you, Git bisecting to an offending prior commit would be extremely useful.

João

**Comment by mfiano** [comment] 2020-12-07 21:29
@joaotavora I would say every 20 minutes to an hour, so not *that* easy to bisect. Is there anything else I can do to help pin it down?

**Comment by joaotavora** [comment] 2020-12-07 21:30
In principle, with the Elisp evaluation model I know, this shouldn't matter, but you can try with this patch:
```
diff --git a/sly.el b/sly.el
index ae88a8ed..ca58bf24 100644
--- a/sly.el
+++ b/sly.el
@@ -2541,8 +2541,8 @@ Debugged requests are ignored."
            (when (and (sly-use-sigint-for-interrupt) (sly-busy-p))
              (sly-display-oneliner "; pipelined request... %S" form))
            (let ((id (cl-incf (sly-continuation-counter))))
-             (sly-send `(:emacs-rex ,form ,package ,thread ,id ,@extra-options))
              (push (cons id continuation) (sly-rex-continuations))
+             (sly-send `(:emacs-rex ,form ,package ,thread ,id ,@extra-options))
              (sly--refresh-mode-line)))
           ((:return value id)
            (let ((rec (assq id (sly-rex-continuations))))
```

**Comment by joaotavora** [comment] 2020-12-07 21:31
The code path that I'm thinking about should be equivalent to SLIME's, so I find this very strange.  Maybe you upgraded Emacs versions a month ago or something like that?

**Comment by mfiano** [comment] 2020-12-07 21:32
I am on Arch Linux, so get frequent updates, yes. Currently on Emacs 27.1

**Comment by joaotavora** [comment] 2020-12-07 21:34
> I am on Arch Linux, so get frequent updates, yes. Currently on Emacs 27.1

That's fairly recent, and what I use as well (actually I use master). Maybe you can downgrade momentarily to 26.3 or keep it besides Emacs 27.

Anyway, this seems to be Eldoc/Autodoc exclusive, so shooshing those errors in those circunstances could be an option.  But I'd like to get to the bottom of it.  Please try my patch for a while.

**Comment by mfiano** [comment] 2020-12-07 21:36
Actually, come to think of it, this started happening when I upgraded from 27 to 27.1 back when it was released in August, but I also updated all my Emacs packages at the same time, so...

**Comment by joaotavora** [comment] 2020-12-07 21:39
From 27 to 27.1?  That's odd.  Were you using a pretest? Or did you mean 26?

**Comment by mfiano** [comment] 2020-12-07 21:42
Let me consult my Linux package update log...

```
[2020-02-21T00:39:27+0000] [ALPM] installed emacs (26.3-1)
[2020-05-22T22:03:46-0400] [ALPM] upgraded emacs (26.3-1 -> 26.3-2)
[2020-08-13T17:39:33-0400] [ALPM] upgraded emacs (26.3-2 -> 27.1-2)
```
Ah, sorry. So it happened with 26.3 -> 27.1.

**Comment by joaotavora** [comment] 2020-12-07 21:43
Nice linux distro btw.  Someday I'll switch myself, what "flavor" of Arch, if any, are you on?

**Comment by mfiano** [comment] 2020-12-07 21:43
Plain old Arch Linux.

**Comment by joaotavora** [comment] 2020-12-07 21:53
Anyway, so as you can see by my patch, my suspicion/working hypothesis is that 27.1 somehow allowed (contrary to 26.3) `sly-send` or its calles to receive output from subprocesses "prematurely".  Basically Eldoc/Autodoc would have responded so damn quickly that there wouldn't have been enough time to run the next statement so when they reply back the "continuation" isn't there and you get that error.  So the solution would be to first register the continuation, and then send `sly-send`.

**Comment by mfiano** [comment] 2020-12-07 21:55
Sure, I am upgrading my packages right now, then I will try your patch, and perhaps Emacs HEAD. Thanks

**Comment by joaotavora** [comment] 2020-12-07 21:55
Actually, I wouldn't do that. I would try one thing at a time.

**Comment by joaotavora** [comment] 2020-12-07 21:56
Starting with the patch, maybe.

**Comment by mfiano** [comment] 2020-12-07 22:23
Yes, I know. I have some other outstanding Emacs issues to take care of too, so first I'm updating packages and inspecting all that. I have a backup on my NAS of the previous state in case things go awful, and to try your patch in isolation.

**Comment by mfiano** [comment] 2020-12-08 00:28
@joaotavora With your patch, eldoc no longer gives any hints at all.

**Comment by mfiano** [comment] 2020-12-08 00:31
In looking over my Emacs config though I have `(setq eldoc-idle-delay 0.1)` which differs from the default of 0.5 because I wanted it more responsive. This leads me to believe there could be some kind of race condition. I will change it to the default in the meantime and see if that helps reduce the chance, even if that is an ugly hack.

**Comment by joaotavora** [comment] 2020-12-08 02:17
> @joaotavora With your patch, eldoc no longer gives any hints at all.

Wow, that is something.  I've pushed a branch with the patch.  Please point your copy of SLY to it, make sure you don't have any stale .elc files, and try to reproduce the problem with a bare Emacs.

**Comment by joaotavora** [comment] 2020-12-08 02:18
> and try to reproduce the problem with a bare Emacs.

By problem I mean _any_ of the two problems, the error or the missing ElDoc. By bare Emacs I mean Emacs -Q.

**Comment by mfiano** [comment] 2020-12-08 02:23
eldoc seems to be working, even though nothing appears to be different from that patch and what i changed. And I always delete elc files between each run in these types of cases. Will keep an eye out for the error now

**Comment by mfiano** [comment] 2020-12-08 03:48
I spoke too soon. eldoc stopped printing out signatures in the minibuffer.

**Comment by joaotavora** [comment] 2020-12-08 10:08
Michael Fiano <notifications@github.com> writes:

> I spoke too soon. eldoc stopped printing out signatures in the minibuffer.

I reproduced this and am looking at it, it's the converse of the error
you got earlier.  You can likely get out of this "no-ElDoc" state with
`M-x sly-forget-pending-events`.  If you have the standard SLY mode-line
you should have spotted a continuation counter stuck at "1" when ElDoc
stopped working.

João

**Comment by joaotavora** [comment] 2020-12-08 10:22
Michael Fiano <notifications@github.com> writes:

> I spoke too soon. eldoc stopped printing out signatures in the minibuffer.

I've pushed another commit to the branch that I'd with you'd try out.

For the record this is related to some mysterious non-local exits when
process-send-string is called from within a timer.  This is likely an
Emacs bug.

It also connects to another strange behaviour I observed recently.

Anyway, try out the patch and let me know.

Cheers.

**Comment by joaotavora** [comment] 2020-12-08 13:42
I've pinned this down to a likely Emacs bug.  Here is the report I made: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45117

@mfiano The most recent commit will probably be the end of it regardless of whether the problem is fixed in Emacs or not, but I'd still appreciate that you'd test it.

**Comment by mfiano** [comment] 2020-12-09 01:05
Interesting. Nice debugging there! I will be using your latest commit and let you know how it goes.

P.S. South Bank Common Lisp is not a thing :)

**Comment by joaotavora** [comment] 2020-12-09 01:08
> P.S. South Bank Common Lisp is not a thing :)

Nah-ah!!!, it's a thing I got here that noone knows and only I use!

:facepalm: :facepalm:

**Comment by mfiano** [comment] 2020-12-09 03:53
Unfortunately, your latest changes didn't solve the issue:

```
error in process filter: sly-dispatch-event: Unexpected reply: 192 (:ok ("(let bindings &body ===> body <===)" t))
error in process filter: Unexpected reply: 192 (:ok ("(let bindings &body ===> body <===)" t))
```

**Comment by joaotavora** [comment] 2020-12-09 08:29
Likely you didn't compile them, or have a stale elc.. I'll look later but you can substitute the latest by the `if` version that prints something everytime it catches the bug. Try that.

**Comment by mfiano** [comment] 2020-12-09 08:46
I made sure to remove all packages, not just ELC, but everything, and did a checkout of that specific branch for Sly.

**Comment by joaotavora** [comment] 2020-12-09 09:19
I still think you missed something.  I'll push a version with a little bit more debugging info and then we can check *Messages* to be sure.

**Comment by joaotavora** [comment] 2020-12-09 09:30
Thinking x2 about it, there is indeed a possibility of unexpected reply, I just never got it (and I got a lot of observations of the bug). but lets run this version so we get more feedback.

**Comment by joaotavora** [comment] 2020-12-09 09:34
By the way, you don't have to completely purge everything to get this, just go to the sly.el file and re-evaluate that definition

**Comment by mfiano** [comment] 2020-12-09 09:35
Give me a few minutes to finish up and I will try. I will say though, that the previous patch seemed to result in the error far less often, or it could just be the computer gods laughing at me. In any case, I will run with the latest for a while and report what I see.

**Comment by mfiano** [comment] 2020-12-09 09:53
After a few minutes, this is in `*Messages*`
```
[sly] Connecting to Slynk on port 41235..
[sly] Connected. Hack and be merry!
[sly] [issue#385] likely `process-send-string' exited non-locally from timer.
[sly] [issue#385] likely `process-send-string' exited non-locally from timer. [2 times]
```

**Comment by joaotavora** [comment] 2020-12-09 09:53
And also some "unexpecteds?"

**Comment by mfiano** [comment] 2020-12-09 09:53
Negative

**Comment by joaotavora** [comment] 2020-12-09 09:54
let's wait though, I think eventually you'll bump into one.

**Comment by mfiano** [comment] 2020-12-09 09:59
I copied some code I already wrote, typing as fast as I could, as that seems to generate them quickly:

```
[sly] Connecting to Slynk on port 41235..
[sly] Connected. Hack and be merry!
[sly] [issue#385] likely `process-send-string' exited non-locally from timer.
No completion found
[sly] [issue#385] likely `process-send-string' exited non-locally from timer. [10 times]
next-line: End of buffer
[sly] [issue#385] likely `process-send-string' exited non-locally from timer. [5 times]
Beginning of buffer [2 times]
```

**Comment by joaotavora** [comment] 2020-12-09 10:00
yeah, with a short `eldoc-idle-delay` it seems to happen very often.   No "unexpecteds" though, right?

**Comment by mfiano** [comment] 2020-12-09 10:01
No unexpecteds with the latest patch.

**Comment by joaotavora** [comment] 2020-12-09 10:01
(the latest patch is the same as the one before, btw :-) just more debugging info)

**Comment by joaotavora** [comment] 2020-12-09 10:02
Anyway, keep testing, I think you'll reach an unexpected or two, by my calculations, it's certainly possible, and likely that was happening before.  It would also explain the perceived decrease in frequency you mentioned.

**Comment by joaotavora** [comment] 2020-12-09 10:03
When you confirm this, I'll have a patch to fix _those_

**Comment by mfiano** [comment] 2020-12-09 10:06
Sure I will keep testing. Just to be clear:

- When the "unexpected"s were frequent, every time they popped up, Emacs would freeze for about 5 seconds.

- When they pop up rarely, they still freeze Emacs for about 5 seconds, but the frequent debug message that is emitted now *does not* freeze Emacs.

**Comment by joaotavora** [comment] 2020-12-09 10:06
By the way.  It's great that you use SLY so intensively _and_ take the time to report these bugs and help me debug them.  Very appreciated :ok_hand:

**Comment by joaotavora** [comment] 2020-12-09 10:07
> When they pop up rarely, they still freeze Emacs for about 5 seconds, but the frequent debug message that is emitted now does not freeze Emacs.


Right, the debug message is just a tracer. You can comment it out.

**Comment by mfiano** [comment] 2020-12-09 10:18
Yep:
```
error in process filter: sly-dispatch-event: Unexpected reply: 1986 (:ok ("(define-compiler-macro make-component (type &rest ===> args <===) &body body)" t))
error in process filter: Unexpected reply: 1986 (:ok ("(define-compiler-macro make-component (type &rest ===> args <===) &body body)" t))
```

**Closed** 2020-12-10 16:39 UTC
Labels: emacs bug

**Comment by joaotavora** [comment] 2020-12-10 16:41
After some very intensive investigation, I came to the correct fix.  I shall be :zap:  if this doesn't fix it.  Problem was in Emacs, but in Elisp and not in C, thankfully.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45117

**Comment by mfiano** [comment] 2020-12-11 02:33
Excellent. Thank you for all your work!
