### ISSUE TITLE
ABCL jump to source-location broken in the debugger

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#98] opened 2016-06-16 08:11 UTC
When in the debuger, pressing v signales an undefined-function condition: The function SLYNK-ABCL::SOURCE-LOCATION is undefined.

This is puzzling as I can see the function defined in the abcl backend and `M-`. works fine.

ABCL: "1.4.0-dev"

**Comment by joaotavora** [comment] 2016-06-18 16:28
> This is puzzling as I can see the function defined in the abcl backend and M-. works fine.

Hmmm. `slynk-abcl::source-location` is indeed an interned symbol, but it has no function definition:

```
#<SYMBOL {64BDB1BB}>
--------------------
Its name is: "SOURCE-LOCATION"
It is unbound.
It has no function value.
It is internal to the package: SLYNK-ABCL [export] [unintern]
Property list: NIL
```

However, `slynk-backend::source-location` does exist and most correctly defined as a function. But it's not an external symbol. So `slynk-abcl` is refering another symbol. The issue is fixed by exporting `slynk-backed::source-location` but I don't know if I should do that.

I think this issue exists in SLIME as well. I'll investigate.

Another thing I can't confirm is the `M-. works fine`. It's completely broken in my ABCL 1.3.3. But it's the first time I'm trying out ABCL, I'll look more into it.

**Comment by PuercoPop** [comment] 2016-06-18 16:37
M-. works for some functions only, try m-. `format` that should work.

**Closed** 2016-06-20 15:01 UTC

**Comment by joaotavora** [comment] 2016-06-20 15:15
Right. Should be fixed now. And `M-.` started working too.
