### ISSUE TITLE
How does one insert "[" or "]" or any other character held captive by the mode map?

### ISSUE THREAD

**Issue by notmgsk** [joaotavora/sly#387] opened 2020-12-15 13:10 UTC
I imagine there must be a reasonably easy way to insert `[` without having it do `lispy-backward`?

**Comment by joaotavora** [comment] 2020-12-15 13:13
Please Mark, give me a recipe.

```
/path/to/emacs -Q -L ~/path/to/sly -l sly-autoloads -f sly 
```
Is usually a great place to start when writing reproduction recipes so that I know what you're talking about.

Also, `lispy-backward` is not in Emacs or Sly.

**Comment by joaotavora** [comment] 2020-12-15 13:15
Closing this to save on my mental bandwidth, will reopen if it turns out to be an actual Sly question/

**Closed by joaotavora** 2020-12-15 13:15 UTC

**Comment by notmgsk** [comment] 2020-12-15 13:37
Speaking of mental bandwidth, I don't know how I ended up posting this issue here and not https://github.com/abo-abo/lispy

:blush:
