### ISSUE TITLE
Out-of-sync REPL output in SBCL, OSX and using a dedicated output stream

### ISSUE THREAD

**Issue by xaransh** [joaotavora/sly#347] opened 2020-09-04 04:52 UTC
Hi, I am trying out the practical Common Lisp book. And running its first demo project shows error in repl prompt display.
The relevant code I am trying out is
`
(defun prompt-read (prompt)
    (format *query-io* "~a: " prompt)
    (force-output *query-io*)
    (read-line *query-io*))
`

`
(defun prompt-for-cd ()
    (make-cd
       (prompt-read "Title")
       (prompt-read "Artist")
       (or (parse-integer (prompt-read "Rating") :junk-allowed t) 0)
       (y-or-n-p "Ripped [y/n]: ")))
`

When I run the prompt-for-cd function, I see only the first prompt and not the later ones.
<img width="348" alt="Screenshot 2020-09-04 at 10 15 22 AM" src="https://user-images.githubusercontent.com/62376184/92200465-8e1da000-ee97-11ea-82f3-1600f304ef99.png">

and when I re run it all the prompt stacked up, show together like this.
<img width="389" alt="Screenshot 2020-09-04 at 10 16 42 AM" src="https://user-images.githubusercontent.com/62376184/92200523-bc02e480-ee97-11ea-8883-07c66c39e226.png">

the only thing I noticed trying to figure out the problem is this emacs message showing

> [sly] some output saved for later insertion.

<img width="460" alt="Screenshot 2020-09-04 at 10 18 01 AM" src="https://user-images.githubusercontent.com/62376184/92200717-36cbff80-ee98-11ea-81d2-26f709137277.png">

It am guessing the problem is somewhere is sly or emacs.
Can anybody help me out please?

**Comment by joaotavora** [comment] 2020-09-04 07:32
Hi @xaransh.  I can't reproduce this with the latest SLY and Emacs, can you pinpoint the versions you used?

Here's what I tried, with `make-cd` being replaced simply by `list`
```lisp
; Dedicated output stream setup (port 39279)
; Redirecting all output to this MREPL
; SLY 1.0.0-beta-3 (#<MREPL mrepl-1-1>)
CL-USER> (defun prompt-read (prompt) (format *query-io* "~a: " prompt) (force-output *query-io*) (read-line *query-io*))
PROMPT-READ
CL-USER> (defun prompt-for-cd () (list (prompt-read "Title") (prompt-read "Artist") (or (parse-integer (prompt-read "Rating") :junk-allowed t) 0) (y-or-n-p "Ripped [y/n]: ")))
PROMPT-FOR-CD
CL-USER> (prompt-for-cd)
Title: hey
Artist: ho
Rating: 42

Ripped [y/n]:  (y or n) n
("hey" "ho" 42 NIL)
CL-USER> 
```

**Comment by xaransh** [comment] 2020-09-04 10:16
emacs version is 27.1 and sly is 1.0.0-beta3

I am using the emacs in macOS Catalina using the emacs-plus version.

**Comment by joaotavora** [comment] 2020-09-04 10:19
Thanks @xaransh , but unfortunately the SLY version you provided is too coarse.  I need to know where you installed it from.

You should be also capable of producing a simple recipe where you start Emacs with no configuration _but_ SLY and then do only the steps that lead to the error.  Otherwise I can't really help you. Meanwhile, I'm marking the bug irreproducible.

**Comment by xaransh** [comment] 2020-09-04 10:21
I installed the sly from Melpa using the package-install. 

I have currently deleted all emacs configuration with just the addition of Melpa repository and sly installation and setting the inferior-lisp. No other configuration.

**Comment by xaransh** [comment] 2020-09-04 10:24
`
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(setq inferior-lisp-program "/usr/local/bin/sbcl")
`

This is all there is in my init-file

**Comment by joaotavora** [comment] 2020-09-04 10:39
Thanks @xaransh , indeed this is very strange.  I will try with Emacs 27.1

**Comment by joaotavora** [comment] 2020-09-04 12:59
I tried again with the latest version of SLY in MELPA and I can't reproduce this.  Maybe you need to upgrade SLY somehow.  You still haven't pinpointed the version.  In which directly does the `sly.el` file live?  Use `M-x find-library` then `sly` to go to that file and find out.

**Comment by xaransh** [comment] 2020-09-04 14:24
sly.el is in ~/.emacs.d/elpa/sly-20200903.1017/sly.el

**Comment by xaransh** [comment] 2020-09-04 14:27
I have tried doing everything from scratch with the installation of emacs, sly, SBCL but still get the same result. 
Using the same functions in SBCL repl is working absolutely fine, and so is with sly with ccl.

**Comment by zzamboni** [comment] 2020-10-26 16:50
@joaotavora I am having the exact same problem as @xaransh. I am using Doom Emacs on macOS, with Emacs 28.0.50, `sly-version` reports `SLY 1.0.0-beta-3`, and the following package versions installed (as part of Doom's `common-lisp` package):
```
(package! sly :pin "fce4f9be39b6a40a4128458ff34151eecb5e27de")
(package! sly-macrostep :pin "5113e4e926cd752b1d0bcc1508b3ebad5def5fad")
(package! sly-repl-ansi-color :pin "b9cd52d1cf927bf7e08582d46ab0bcf1d4fb5048")
```

I'd be happy to provide more information.

Thanks in advance!

**Comment by joaotavora** [comment] 2020-10-26 17:05
bq. I'd be happy to provide more information.

Can you reproduce this with Emacs and none of your customization except Sly?

**Comment by joaotavora** [comment] 2020-10-26 17:10
Wonder if this is Mac OSX specific.... Maybe SBCL on OSX isn't flushing stdout as fast as it does on Linux.

**Comment by zzamboni** [comment] 2020-10-26 19:42
I am getting the same behavior on plain Emacs, with only sly loaded:
![image](https://user-images.githubusercontent.com/32876/97220359-a80a9d80-17cb-11eb-95a0-47ecf8c47801.png)

Maybe it is macOS-specific. Anything I could try to try and isolate the problem?

**Comment by rprimus** [comment] 2020-10-27 08:09
Tue Oct 27 08:02:34 GMT 2020

Setting the following (in `~/.slynkrc`) eliminates the problem:
```
(setf slynk:*use-dedicated-output-stream* nil)
```

See https://github.com/joaotavora/sly/issues/196#issuecomment-436064015 for an explanation.

**Comment by xaransh** [comment] 2020-10-27 09:14
Thanks.

Saransh Mohapatra

**Comment by joaotavora** [comment] 2020-10-27 09:21
Thanks @rprimus .  I'll just note that the expected behaviour is for this to work even with `slynk:*use-dedicated-output-stream*`. I think this has to do with the default "flushing" configuration on SBCL/Mac OSX

**Comment by rprimus** [comment] 2020-10-27 11:09
Tue Oct 27 10:51:32 GMT 2020

> I'll just note that the expected behaviour is for this to work even with slynk:*use-dedicated-output-stream*

### Update: Using `slynk:*communication-style*`

Leaving `slynk:*use-dedicated-output-stream*` unmodified, the following observations have been made:
1.  `SBCL` produces the previously observed symptoms with `slynk:*communication-syle*` set to the default `:SPAWN`.  All other values work fine:
    `:SIGIO`, `:FD-HANDLER` or `NIL`
2. `CCL` *only* starts with the default: `:SPAWN` and does not start with all others.

**Comment by zzamboni** [comment] 2020-10-27 13:10
@rprimus thanks for the tip! Setting `slynk:*use-dedicated-output-stream*` to `nil` as in your first example works for me. I don't know enough Common LISP nor about `sly` to understand what are the consequences of setting `slynk:*communication-style*` to the different values you mention in your second comment. I am using SBCL. What would be your recommendation?

**Comment by joaotavora** [comment] 2020-10-27 13:12
> What would be your recommendation?

Keep the defaults.  Except for `slynk:*use-dedicated-output-stream*` which you need to work around this bug.

**Comment by joaotavora** [comment] 2021-03-05 09:21
Closing this in favour of #426, which is basically the same.

**Closed by joaotavora** 2021-03-05 09:21 UTC
Labels: irreproducible
