### ISSUE TITLE
Unable to start slynk-server from emacs

### ISSUE THREAD

**Issue by pellenation** [joaotavora/sly#329] opened 2020-06-16 20:45 UTC
Hi im running doom emacs `emacs version 26.3` on `osx 10.15.5` . Im having trouble binding to a slynk server when i try to open a lisp file. 

Im getting this error:

```
SLYNK's ASDF loader finished.
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [USE-VALUE] Try a port other than 0
  1: [ABORT    ] Exit debugger, returning to top level.

(SB-BSD-SOCKETS:SOCKET-ERROR "bind" 49)
   source: (ERROR (CONDITION-FOR-ERRNO ERRNO) :ERRNO ERRNO :SYSCALL WHERE)
```

It would be great if someone could point me in the correct direction.

**Comment by joaotavora** [comment] 2020-06-16 20:54
Hello @pellenation, unfortunately, with that amount of information it's very hard to help you.  I don't know very well what "Doom" emacs is (and I don't have a lot of time to find out).  I just know GNU Emacs. Please read this very short section https://github.com/joaotavora/sly/blob/master/CONTRIBUTING.md#reporting-bugs.  Can you get that example working?  osx has a "Terminal" application where you can try to run those commands.

In general you should be able to describe to a total newbie how to reproduce the problem exactly how it happened to you.  The problem is likely in your configuration, and we could try to help, but it's hard if you only give me that context.

**Comment by pellenation** [comment] 2020-06-17 20:23
Oh im sorry! I didnt read that. Ill try again :) 

I removed doom emacs and started from the beginning without any other customizations.

1. `Emacs 26.3`
2. `SBCL 2.0.5`

When i try to run `emacs -Q -L . -l sly-autoloads --eval '(setq inferior-lisp-program "sbcl")' -f sly` i get the same error as my first post. 

Emacs starts up and sly starts polling `[sly] Polling "/var/folders/03/sng_mnzn2ys6zggg4ykhp1zr0000gp/T/sly.20656" .. 42 (Abort with 'M-x sly-abort-connection'.)`

Nothing happens in emacs but in the terminal i get this error. 

```
SLYNK's ASDF loader finished.
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [USE-VALUE] Try a port other than 0
  1: [ABORT    ] Exit debugger, returning to top level.

(SB-BSD-SOCKETS:SOCKET-ERROR "bind" 49)
   source: (ERROR (CONDITION-FOR-ERRNO ERRNO) :ERRNO ERRNO :SYSCALL WHERE)
0]
```

**Comment by joaotavora** [comment] 2020-06-17 22:10
> Oh im sorry! I didnt read that. Ill try again :)

No problem

> i get the same error as my first post.

Right.  So you reproduced it.  Now I know it's either a SLY problem, or a problem with that particular version of SBCL.

> Nothing happens in emacs but in the terminal i get this error.

What exactly do you mean: "the terminal".  Are you referring to the OSX "Terminal" or to a "buffer" in Emacs called `*... inferior lisp ...*"`.  Can you post a screenshot?

**Comment by pellenation** [comment] 2020-06-18 20:51
Im sorry if i was unclear regarding the terminal.

what i ment with the terminal was the osx terminal. 

here are some screenshots of whats happening.

<img width="818" alt="Skärmavbild 2020-06-18 kl  22 49 28" src="https://user-images.githubusercontent.com/1358130/85070375-fc669680-b1b5-11ea-93c2-3895a91e0948.png">

<img width="707" alt="Skärmavbild 2020-06-18 kl  22 49 17" src="https://user-images.githubusercontent.com/1358130/85070421-0e483980-b1b6-11ea-8cb7-931d2c3c0f48.png">

hope this helps :)

**Comment by joaotavora** [comment] 2020-06-18 21:11
This is very  bizarre.  I don't understand how SBCL can be outputting to the Terminal directly if it's been started as an inferior process to Emacs.  How exactly did you install SBCL?

**Comment by pellenation** [comment] 2020-06-18 21:27
I installed sbcl via homebrew. I think it might be something wrong with the sbcl version or the way homebrew installs sbcl?

I tried clisp as the inferior-lisp-program `(setq inferior-lisp-program "/usr/local/bin/clisp")`
and now sly started. 

what is the recommended way to install sbcl on osx?

**Comment by joaotavora** [comment] 2020-06-18 21:29
> what is the recommended way to install sbcl on osx?

Good question.  Ask sbcl developers? Maybe my friend @luismbo can help, he hacks a bit on it.

**Comment by rprimus** [comment] 2020-06-19 00:08
Fri Jun 19 01:02:16 BST 2020

@pellenation - Have you tried using the full path to `sbcl` - `/usr/local/bin/sbcl` - as done with  `clisp`?

Is it possible that there exists a shell alias for `sbcl` -  in the terminal, what's the output for `which sbcl`?

**Comment by rprimus** [comment] 2020-06-19 00:22
Fri Jun 19 01:17:34 BST 2020

Searching for the error `Try a port other than 0` brings up:

https://github.com/slime/slime/issues/402

The important bit:
> The source of the problem is that on a misconfigured system gethostbyname("localhost") can go out to your external nameserver, and that will probably return something other than 127.0.0.1.

What does

**Comment by rprimus** [comment] 2020-06-19 05:49
Fri Jun 19 06:47:02 BST 2020

@joaotavora - an easy way to simulate this is to (temporarily) change the entry for `localhost` in `/etc/hosts` to `127.0.0.2` and run the `emacs -Q ...` test.

**Comment by mdbergmann** [comment] 2020-06-19 06:53
I'm also using sbcl via Homebrew.
But it's working fine, at least when run via M-x sly in an already open Emacs.

**Comment by luismbo** [comment] 2020-06-19 12:20
@joaotavora @pellenation I haven't owned a Mac in a while, but what does `Emacs -Q --eval '(display-buffer (make-comint "test-buffer" "bash" nil "-c" "echo \"hello world\" > /dev/tty"))'` do? Does it print "hello world" to the terminal or to the Emacs buffer?

**Comment by joaotavora** [comment] 2020-06-19 12:43
@luismbo Thanks for the recipe. On linux, it ends up in the Emacs buffer,  including when I replace `/dev/tty` with `/dev/stdout` or `/dev/stderr`.

I've also tried with
```
emacs -Q --eval '(display-buffer (make-comint "test-buffer" "sbcl" nil "--eval" "(error \"hello world\")"))'
```
That _also_ ends up in the Emacs buffer (and you interact with the live process through that same buffer). @pellenation try that one too, please.

**Comment by rprimus** [comment] 2020-06-19 18:30
Fri Jun 19 19:02:45 BST 2020

@joaotavora  Here is a gif showing what happens on macOS when `localhost` is unreachable:

![sly-test-3](https://user-images.githubusercontent.com/278414/85167000-a813f300-b257-11ea-8682-4e24ab5c666a.gif)

1. When using `ccl`, nothing happens in the terminal,  however, `SLYNK` does not start - polling attempts keep increasing until either killing process in terminal or `sly-abort-connection` in buffer.

`backend/sbcl.lisp` `create-socket` code is the only `defimplementation` to use `resolve-host`.

2. On macOS, the above two tests produce results in a buffer.

HTH in resolving @pellenation 's problem.

**Comment by joaotavora** [comment] 2020-06-19 18:35
> When using ccl, nothing happens in the terminal, however, SLYNK does not start - polling attempts keep increasing until either killing process in terminal or sly-abort-connection in buffer.

This is what I expected in sbcl too.

Indeed, I'm being distracted by the bizarre  fact that the `sbcl` program somehow manages to print directly to the tty, but the actual problem of @pellenation is likely fixed by what @rprimus is suggesting: get your `localhost` resolution to work correctly.

Or maybe I should just cherry-pick https://github.com/slime/slime/issues/402

**Comment by rprimus** [comment] 2020-06-19 18:40
Fri Jun 19 19:39:57 BST 2020

Didn't you already do that with https://github.com/joaotavora/sly/commit/080a8f718e23428f057fe4686152eb05dc75506f

**Comment by pellenation** [comment] 2020-06-20 20:32
Hi, sorry for the delay.

@rprimus I have tried to add the full path to sbcl and it doesn't work.
when i run `which sbcl` i get `/usr/local/bin/sbcl`.

output for `ping -c 3 localhost`

```text
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.058 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.045 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.060 ms

--- localhost ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.045/0.054/0.060/0.007 ms
```

when i run `emacs -Q --eval '(display-buffer (make-comint "test-buffer" "sbcl" nil "--eval" "(error \"hello world\")"))'`

<img width="707" alt="Skärmavbild 2020-06-20 kl  22 26 44" src="https://user-images.githubusercontent.com/1358130/85211055-c0623b80-b345-11ea-976a-3be7bc16d625.png">

when i run `emacs -Q --eval '(display-buffer (make-comint "test-buffer" "sbcl" nil "--eval" "(sb-thread:make-thread (lambda () (error \"hello world\")))"))'`

<img width="707" alt="Skärmavbild 2020-06-20 kl  22 31 43" src="https://user-images.githubusercontent.com/1358130/85211067-d3750b80-b345-11ea-9753-5530104c7fb1.png">

**Comment by pellenation** [comment] 2020-06-20 20:51
I checked my hosts file and found a weird entry. 

```text
127.0.0.1		        localhost
192.168.0.2		localhost
255.255.255.255	broadcasthost
::1				localhost
fe80::1%lo0		localhost
```

removed second entry

```text
127.0.0.1		        localhost
255.255.255.255	broadcasthost
::1				localhost
fe80::1%lo0		localhost
```

Now everything works as expected! Thanks for all the help 👍

**Comment by rprimus** [comment] 2020-06-21 09:58
Sun Jun 21 10:43:20 BST 2020

For future reference to anyone on macOS with this problem:
to check dns resolution of `localhost`, use `dns-sd -q localhost`:
```
: ; dns-sd -q localhost
DATE: ---Sun 21 Jun 2020---
10:45:09.054  ...STARTING...
Timestamp     A/R    Flags if Name                          Type  Class   Rdata
10:45:09.056  Add 40000002 -1 localhost.                    Addr   IN     127.0.0.1
```

This would cause a problem if:
1.  the IP not `127.0.0.1` or
2.  there are multiple entries, *AND* the additional IP addresse(s) are not bound to an interface on the machine :

```
: ; dns-sd -q localhost
DATE: ---Sun 21 Jun 2020---
10:49:58.939  ...STARTING...
Timestamp     A/R    Flags if Name                          Type  Class   Rdata
10:49:58.940  Add 40000003 -1 localhost.                    Addr   IN     127.0.0.1
10:49:58.940  Add 40000002 -1 localhost.                    Addr   IN     192.168.100.10
```
```
: ; ifconfig -a | ag -i 192.168.100.10 | wc -l
       0
```

**Closed** 2020-06-21 20:32 UTC
Labels: irreproducible
