### ISSUE TITLE
Helm completion stops working after a41e6900

### ISSUE THREAD

**Issue by thierryvolpiatto** [joaotavora/sly#348] opened 2020-09-04 06:16 UTC
I checked out a41e6900 and it is working, but perhaps some earlier versions are working as well.
Anyway with recentest, completion hangs several minutes before failing silently.
Configured like this:

``` elisp
(require 'sly-autoloads)
(setq inferior-lisp-program "/usr/bin/sbcl")
(add-hook 'sly-mode-hook (lambda () (sly-symbol-completion-mode -1)))
```

Did I miss something?

Thanks.

**Comment by joaotavora** [comment] 2020-09-04 06:46
> I checked out a41e690 and it is working, but perhaps some earlier versions are working as well.

Did you mean "perhaps some later versions are working as well"?  If so, can you bisect it?

Or did you mean that a41e690 is the last commit where completion is working?

**Comment by thierryvolpiatto** [comment] 2020-09-04 07:07
After bisecting, it break at d4e52fe7, previous versions are working.

So:
Last good commit: 36aea9aa
Fist bad commit:    d4e52fe7
``` git
d4e52fe7fd31ed408bc60608416f785949b95133
Author:     João Távora <joaotavora@gmail.com>
AuthorDate: Thu Dec 19 23:29:47 2019 +0100
Commit:     João Távora <joaotavora@gmail.com>
CommitDate: Thu Dec 19 23:45:44 2019 +0100

Parent:     36aea9aa Make trace dialog abbreviate spec names like the inspector
Contained:  master
Follows:    slime-catchup-2.21 (147)

Simplify sly-eval.  Attempt to avoid stale continuations

Elisp/Lisp flow control sometimes still produces stale continuations
sometimes appear in some hard-to-reproduce scenarios that aren't still
totally clear to me.  Take a hint from Emacs lisp/jsonrpc.el's
jsonrpc-request function and don't mess with inhibit-quit or
quit-flag.

The only confirmed user-visible difference is that C-g'ing
immediately after::

  (sly-eval '(cl:progn (cl:sleep 42) 'hmmm))

Would lead to an error 42 seconds later.

* sly.el (sly--stack-eval-tags): Rename from sly-stack-eval-tags.
Document.
(sly-eval): Simplify.
(sly-db-setup): Use sly--stack-eval-tags
```

**Comment by thierryvolpiatto** [comment] 2020-09-04 07:12
Note that completion without `helm-mode` enabled works as expected, and with `sly-symbol-completion-mode` enabled as well, didn't try with company and others UI.

**Comment by joaotavora** [comment] 2020-09-04 07:20
Alright.  Thanks @thierryvolpiatto: this seems to be a duplicate of #303 .  Let's continue the discussion there.

**Closed by joaotavora** 2020-09-04 07:20 UTC
