### ISSUE TITLE
Incessant "no comment syntax is defined" when using aggressive-indent-mode

### ISSUE THREAD

**Issue by vermiculus** [joaotavora/sly#112] opened 2017-03-05 14:16 UTC
I really recommend starting this in a fresh session since you'll have to kill emacs.

Start `emacs -Q` with the following:

```elisp
(require 'package)
(package-initialize)

(require 'sly)
(setq inferior-lisp-program "sbcl")

(require 'aggressive-indent)
(aggressive-indent-global-mode)
```

Start Sly with `M-x sly`. Now, no matter what you type, you'll be presented with a `No comment syntax is defined.` prompt.

```
(require 'package)
(package-initialize)

(require 'sly)
(setq inferior-lisp-program "sbcl")

(require 'aggressive-indent)
(aggressive-indent-global-mode)

-UU-:----F1  init.el        All L1    Git:master  (Emacs-Lisp =>) --------------
;      \   ) \     ) \ \                                                        
;       ) /__ \__  ) (\ \___                                                    
; jgs  (___)))__))(__))(__)))                                                   
;                                                                               
; Redirecting all output to this MREPL                                          
; SLY 1.0.0-beta-2 (#<MREPL mrepl-1-1>)                                         
CL-USER> 



-UUU:**--F1  *sly-mrepl for sbcl*   Bot L15    (mrepl =>)  [sly sbcl/*/-/-/QL] -
No comment syntax is defined.  Use: 
```

**Comment by vermiculus** [comment] 2017-03-05 14:23
As a workaround, adding `(setq aggressive-indent-excluded-modes '(comint-mode))` will resolve the issue by excluding `aggressive-indent-mode` from the REPL.

**Comment by joaotavora** [comment] 2017-03-05 20:28
Nice. I wonder if it makes sense to use aggressive indent mode in the REPL. If so, then perhaps defining a comment syntax could do the trick. I don't have sly handy right now, maybe you can try it. I think just invoking `m-x comment-dwim` interactively should prompt you to enter a syntax. Just use `;` or something...

**Comment by vermiculus** [comment] 2017-03-05 20:34
The problem is, no matter how many times I provide a comment syntax, it keeps asking…

**Comment by joaotavora** [comment] 2017-03-05 22:24
Curiously enough, I couldn't reproduce it without your recipe. 

Anyway, setting `comment-start` to `";"` in the REPL seems the right thing to do... Should be fixed now.

**Closed** 2017-03-05 22:24 UTC
