### ISSUE TITLE
Whitespace at the start of the line makes C-c C-c eva/compile the next form

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#111] opened 2017-02-27 04:27 UTC
For example write the following in test.lisp (or sly-scratch)
```lisp
(in-package "CL-USER")

(defmacro foo ()
  (format t "Evaluating FOO~%"))

(defmacro bar ()
  (format t "Evaluating BAR~%"))

 (foo)

(bar)
```

Place your cursor anywhere in the line of the third form (ie `(foo)`) and you'll see that (bar) is what gets evaluated

**Comment by joaotavora** [comment] 2017-03-05 12:04
ACK. I'll try to analyse this later today (and slowly get back to hacking in general :-))

**Comment by joaotavora** [comment] 2017-03-05 22:38
Silly bug indeed.

**Comment by joaotavora** [comment] 2017-03-05 22:54
Hmmm, I'm not sure it's a bug now, or at least not a bug in SLY. SLIME has the same problem. It's easily fixed by setting `open-paren-in-column-0-is-defun-start` to `nil`, either globally or in `sly-editing-mode-hook`, for instance.

But keep an eye on https://www.gnu.org/software/emacs/manual/html_node/emacs/Left-Margin-Paren.html

It says that setting it to nil could affect performance of basic things like scrolling and stuff, perhaps you can try for a few days and tell me what your thoughts are. I haven't noticed anything, but then I haven't been hacking much :-). Try it out:

```lisp
(add-hook 'sly-editing-mode-hook 
  (lambda () (setq-local open-paren-in-column-0-is-defun-start nil)))

**Comment by PuercoPop** [comment] 2017-03-05 23:50
Well the behaviour although silly is not a common use case. I only stumbled upon it due to copying and pasting. If it is due to emacs we can close this

**Closed** 2017-03-05 23:50 UTC
Labels: workaround
