### ISSUE TITLE
Sly hangs after several reads.

### ISSUE THREAD

**Issue by commander-trashdin** [joaotavora/sly#335] opened 2020-07-13 21:39 UTC
It's hard to specify the exact number, but it varies from 1 to 4.

I'm using Debian, latest sbcl and Emacs (doom) 28. I checked this with bare sbcl repl and it does not have this issue. However, when I call `(read) in sly repl, after several calls it hangs after I hit RET. There's no way to get it out of this state other than disconnect. I was testing it with very simple forms to avoid somehow messing up parentheses or whatnot.

P.S. hangs = just goes into "Repl is busy" stuck mode.

**Comment by joaotavora** [comment] 2020-07-13 22:06
I very much think this is a duplicate of #313.  Let's close this and handle it there.  If you show this is a separate problem, I will reopen.

**Closed by joaotavora** 2020-07-13 22:06 UTC

**Comment by commander-trashdin** [comment] 2020-07-13 22:33
Ah, no worries. If I could find that issue myself (I couldn't) I would rather comment there. That said, it doesn't look like any sort of repl abuse to me:) it is literally no more than 6 calls to read. 

I cannot recall if same happens to read-line, but I suspect the answer is yes.

**Comment by joaotavora** [comment] 2020-07-13 23:33
> it is literally no more than 6 calls to read.

But does it also happen when you try those 6 `read` calls slowly one at a time?  Or is it only when you hold down enter or otherwise give input very quickly?

**Comment by commander-trashdin** [comment] 2020-07-13 23:45
Yes, it was one at a time. More than that, sometimes just one call to read is enough.

**Comment by joaotavora** [comment] 2020-07-13 23:48
Then it might very well be a different issue.  Can you please try to reproduce this without "doom", like I explain in https://github.com/joaotavora/sly/blob/master/CONTRIBUTING.md#reporting-bugs?

**Comment by joaotavora** [comment] 2020-07-19 11:17
I've tried to reproduce this in my own Emacs configuration which is fairly lean, and I couldn't.

**Comment by joaotavora** [comment] 2020-07-19 11:20
When you get to see this again (if you do), please paste the last few line of the `*sly-events for xxx*` and `*Messages*` buffers.
