### ISSUE TITLE
Loading Sly on .lisp file open - launches debugger in inferior lisp for sbcl.

### ISSUE THREAD

**Issue by Harag** [joaotavora/sly#446] opened 2021-05-14 06:39 UTC
When loading sly on opening .lisp file the following warning causes a debugger session in *sly-inferior-lisp for sbcl*

This is SBCL 2.0.6.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>
......

* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
SLYNK's ASDF loader finished.
debugger invoked on a FILE-EXISTS in thread
#<THREAD "main thread" RUNNING {10009F0083}>:
  Error opening #P"/tmp/sly.61169"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [SUPERSEDE] Reopen with :if-exists :supersede
  1: [OVERWRITE] Reopen with :if-exists :overwrite
  2: [RENAME   ] Reopen with :if-exists :rename
  3: [APPEND   ] Reopen with :if-exists :append
  4: [CONTINUE ] Retry opening.
  5: [USE-VALUE] Try opening a different file.
  6: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::FILE-PERROR #P"/tmp/sly.61169" 17 FILE-EXISTS :FORMAT-CONTROL "Error opening ~S" :FORMAT-ARGUMENTS (#P"/tmp/sly.61169"))

**Comment by Harag** [comment] 2021-05-14 06:43
M-x sly does not exhibit the same behaviour.

**Comment by joaotavora** [comment] 2021-05-14 06:58
YOu have to provide a proper issue report and fully explain what "loading sly on opening .lisp file" means.  See https://github.com/joaotavora/sly/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by Harag** [comment] 2021-05-15 09:05
## Versions

$ /snap/bin/emacs -version
GNU Emacs 27.2
Copyright (C) 2021 Free Software Foundation, Inc.

$ /usr/local/bin/sbcl --version
SBCL 2.1.4.32-ef1ff011f

## Init file

Contents of .emacs-bare :

(require 'package)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

(package-initialize)
(package-refresh-contents)

(dolist (package '(sly))
  (unless (package-installed-p package)
     (package-install package)))

(setq sly-lisp-implementations
      '(;;(ccl ("ccl"))
        (sbcl ("/usr/local/bin/sbcl" "--dynamic-space-size" "24000") :coding-system utf-8-unix)))

;;Load sly when .lisp file is opened
(add-hook 'sly-mode-hook
          (lambda ()
            (unless (sly-connected-p)
              (save-excursion (sly)))))

## Command to load emacs

/snap/bin/emacs -Q -l /home/phil/.emacs-bare

## Steps after loading emacs

When emacs is open and loaded open any file that ends in a .lisp extension. Sly mrepl will be loaded and focus will have moved to mrepl. Now check in your buffer menu for *sly-inferior-lisp for sbcl* and you will see the following:

This is SBCL 2.1.4.32-ef1ff011f, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
SLYNK's ASDF loader finished.
debugger invoked on a FILE-EXISTS in thread
#<THREAD "main thread" RUNNING {1001548103}>:
  The file #P"/tmp/sly.84327" already exists: File exists

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [SUPERSEDE] Reopen with :if-exists :supersede
  1: [OVERWRITE] Reopen with :if-exists :overwrite
  2: [RENAME   ] Reopen with :if-exists :rename
  3: [APPEND   ] Reopen with :if-exists :append
  4: [CONTINUE ] Retry opening.
  5: [USE-VALUE] Try opening a different file.
  6: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::FILE-PERROR #P"/tmp/sly.84327" 17 FILE-EXISTS)
0] 

If I start up emacs with the exact same config and do M-x sly then I do not get the same error in *sly-inferior-lisp for sbcl*.

## Expected result 

No error in inferior buffer.

**Comment by joaotavora** [comment] 2021-05-15 09:13
Thanks, this is better now.  I'll try to reproduce it later today or tomorrow.  Is that final `Load sly when .lisp file opened` from the manual, from another place, or did you come up with it yourself?

**Comment by Harag** [comment] 2021-05-15 09:37
From the manual the following section

## 8.3 Connecting to SLY automatically

To make SLY connect to your lisp whenever you open a lisp file just add this to your ‘~/.emacs’ or ‘~/.emacs.d/init.el’ (see Emacs Init File):

```
(add-hook 'sly-mode-hook
          (lambda ()
            (unless (sly-connected-p)
              (save-excursion (sly)))))

```

**Comment by joaotavora** [comment] 2021-05-16 10:14
Hi @Harag , so I was looking into this, and I can't reproduce it with your recipe.  However, I don't particularly like that snippet as it is recommended in the manual, as it seems to have the potential to attempt to start two `sly` sessions concurrently, which is probably unwanted and problematic.  I will keep investigating, but can you try this patch, re-run your problematic case, and tell me what happens in the `*Messages*` buffer thereafter?

```lisp
diff --git a/sly.el b/sly.el
index 8a5273f2..9eb3f37e 100644
--- a/sly.el
+++ b/sly.el
@@ -1076,6 +1076,7 @@ prefix argument controls the precise behaviour:
   for a symbol indexing one of the entries in
   `sly-lisp-implementations'"
   (interactive (list nil nil t))
+  (message "sly() being called")
   (sly--when-let*
       ((active (and interactive
                     (not current-prefix-arg)
```

We expect only one `"sly() being called"`.  if there's two, the aforementioned concurrency problem exists.

After this experiment is done, I ask you to try the same experiment with this snippet instead:

```
(add-hook 'sly-editing-mode-hook
          (lambda ()
            (unless (sly-connected-p)
              (save-excursion (sly)))))
```

(notice the `sly-editing-mode-hook` instead of `sly-mode-hook`)

**Comment by Harag** [comment] 2021-05-17 03:51
Hi @joaotavora 

I just hacked the code I got from melpa but get an error trying to compile it or loading it from .el

Compiling file /home/phil/.emacs.d/elpa/sly-20210303.1148/sly.el at Mon May 17 05:38:00 2021
sly.el:745:1:Error: Invalid read syntax: ". in wrong context"

Which points at 

(defmacro sly-dcase (value &rest patterns)
  (declare (indent 1)
           (debug (sexp &rest (sexp &rest form))))
...

**Comment by Harag** [comment] 2021-05-17 04:30
@joaotavora it gets more involved. I did a couple more tests and this is what transpired:

Scenario 1:

1. I delete all sly from .emacs.d
2. Open emacs with my .emacs-bare, it downloads and compiles sly
3. Open a .lisp file and sly mrepl starts up fine 
4. At this stage I have the following buffers
*sly-inferior-lisp for sbcl*
*sly-events for sbcl*
*sly-mrepl for sbcl*
5. There are no errors in the *sly-inferior-lisp for sbcl*
6. Shut down emacs

Scenario 2:

1. Start up emacs again after Scenario 1.
2. Open a .lisp file and sly mrepl starts up fine 
3. At this stage I have the following buffers
*sly-started inferior-lisp for sbcl*
*sly-inferior-lisp for sbcl*
*sly-events for sbcl*
*sly-mrepl for sbcl*
4. Now I have the File already exists in *sly-inferior-lisp for sbcl*.

Here is the content for *sly-started inferior-lisp for sbcl*

```
(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "/home/phil/.emacs.d/elpa/sly-20210303.1148/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "/tmp/sly.163687")) (t (progn (load "/home/phil/.emacs.d/elpa/sly-20210303.1148/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "/tmp/sly.163687"))))

This is SBCL 2.1.4.32-ef1ff011f, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
;; Slynk started at port: 36563.
SLYNK's ASDF loader finished.
36563
* WARNING: redefining SLYNK::SYMBOL-INDENTATION in DEFUN
WARNING: redefining SLYNK::MACRO-INDENTATION in DEFUN
```

Here is the content for *sly-inferior-lisp for sbcl*

```
(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "/home/phil/.emacs.d/elpa/sly-20210303.1148/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "/tmp/sly.163687")) (t (progn (load "/home/phil/.emacs.d/elpa/sly-20210303.1148/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "/tmp/sly.163687"))))

This is SBCL 2.1.4.32-ef1ff011f, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
SLYNK's ASDF loader finished.
debugger invoked on a FILE-EXISTS in thread
#<THREAD "main thread" RUNNING {1001548103}>:
  The file #P"/tmp/sly.163687" already exists: File exists

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [SUPERSEDE] Reopen with :if-exists :supersede
  1: [OVERWRITE] Reopen with :if-exists :overwrite
  2: [RENAME   ] Reopen with :if-exists :rename
  3: [APPEND   ] Reopen with :if-exists :append
  4: [CONTINUE ] Retry opening.
  5: [USE-VALUE] Try opening a different file.
  6: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::FILE-PERROR #P"/tmp/sly.163687" 17 FILE-EXISTS)
0] 
```

Using your "new" code snippet produces the same results if I run the exact same scenarios.

**Comment by rprimus** [comment] 2021-05-17 08:38
Mon May 17 09:19:14 BST 2021

@Harag If the following files exist, please provide their contents:
1. `${HOME}/.sbclrc`
2. `${HOME}/.slynkrc`

Also, please provide the output from `M-x sly-version`

If `${HOME}/.sbclrc` does exist, please change `sly-lisp-implementations` in `.emacs-bare` to:

```
(setq sly-lisp-implementations
      '(sbcl ("/usr/local/bin/sbcl" "--no-userinit") :coding-system utf-8-unix)))
```

and see if the error persists.

**Comment by Harag** [comment] 2021-05-17 09:20
## .slynkrc

Does not exist

## .sbclrc

```
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

## Sly Version

SLY 1.0.43

## --no-userinit

Tried with --no-userinit and the issue persists.

**Comment by joaotavora** [comment] 2021-05-17 09:27
@Harag in "Scenario 2" you write "Open a .lisp file and sly mrepl starts up fine" . Are you sure about this, does it really start up "fine"?

@rprimus I take it also can't reproduce this?

@Harag maybe Emacs is having a hard time deleting a previously created file.  Can you try with this change to `sly.el`? (then sure you delete the `sly.elc` file before retrying the load.  Loadinf Sly from Git may be simpler, too).

```diff
diff --git a/sly.el b/sly.el
index 8a5273f2..5af62dea 100644
--- a/sly.el
+++ b/sly.el
@@ -1323,7 +1323,7 @@ Return the created process."
 
 (defun sly-inferior-connect (process args)
   "Start a Slynk server in the inferior Lisp and connect."
-  (sly-delete-slynk-port-file 'quiet)
+  (sly-delete-slynk-port-file t)
   (sly-start-slynk-server process args)
   (sly-read-port-and-connect process))
 
```

**Comment by Harag** [comment] 2021-05-17 09:57
# Testing with GIT code

Tested with and without  message in place and  t instead of 'quiet, the results where the same.

The one thing that changes "some times" between tests is which buffer has the actual error in *sly-started inferior-lisp for sbcl* or *sly-inferior-lisp for sbcl*

## *Messages* buffer when message in place
```
For information about GNU Emacs and the GNU system, type C-h C-a.
sly() being called
[sly] Polling "/tmp/sly.182916" .. 1 (Abort with `M-x sly-abort-connection'.)
sly() being called
[sly] Polling "/tmp/sly.182916" .. 1 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.182916" .. 2 (Abort with `M-x sly-abort-connection'.)
[sly] Connecting to Slynk on port 38367..
[sly] Connected. Let the hacking commence!
```

## Steps

1. Deleted all sly directories in .emacs.d
2. https cloned git repository (M-x sly-version = SLY 1.0.43)
3. .emacs-bare
```
(add-to-list 'load-path "/home/phil/.emacs.d/sly")
(require 'sly-autoloads)

;;Can use M x sly [name of implementation]
(setq sly-lisp-implementations
      '((sbcl ("/usr/local/bin/sbcl" "--no-userinit") :coding-system utf-8-unix)))

(add-hook 'sly-editing-mode-hook
          (lambda (); 
            (unless (sly-connected-p)
              (save-excursion (sly)))))
```
4. Loaded emacs with 
```
/snap/bin/emacs -Q -l /home/phil/.emacs-bare
```
5. Opened a file with .lisp extension
6. mrepl shows fine; 
```
;        Hacks and glory await!
;                   .
;            __..--''``\--....___   _..,_
;        _.-'    .-/";  `        ``<._  ``-+'~=.
;    _.-' _..--.'_    \                    `(^) )
;   ((..-'    (< _     ;_..__               ; `'
;              `-._,_)'      ``--...____..-'
;                                       fxlee
; 
; Dedicated output stream setup (port 34141)
; Redirecting all output to this MREPL
; SLY 1.0.43 (#<MREPL mrepl-1-1>)
CL-USER> (+ 1 2)
3 (2 bits, #x3, #o3, #b11)
CL-USER> 
```
7. At this stage I have the following buffers
*sly-started inferior-lisp for sbcl*
*sly-inferior-lisp for sbcl*
*sly-events for sbcl*
*sly-mrepl for sbcl*

## Results
*sly-started-inferior-lisp for sbcl* has the follwoing content
```
(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "/home/phil/.emacs.d/sly/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "/tmp/sly.182122")) (t (progn (load "/home/phil/.emacs.d/sly/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "/tmp/sly.182122"))))

This is SBCL 2.1.4.32-ef1ff011f, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
SLYNK's ASDF loader finished.
debugger invoked on a FILE-EXISTS in thread
#<THREAD "main thread" RUNNING {1004AB8173}>:
  The file #P"/tmp/sly.182122" already exists: File exists

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [SUPERSEDE] Reopen with :if-exists :supersede
  1: [OVERWRITE] Reopen with :if-exists :overwrite
  2: [RENAME   ] Reopen with :if-exists :rename
  3: [APPEND   ] Reopen with :if-exists :append
  4: [CONTINUE ] Retry opening.
  5: [USE-VALUE] Try opening a different file.
  6: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::FILE-PERROR #P"/tmp/sly.182122" 17 FILE-EXISTS)
0] 
```

*sly-inferior-lisp for sbcl* has the following content

```
 (cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "/home/phil/.emacs.d/sly/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "/tmp/sly.182122")) (t (progn (load "/home/phil/.emacs.d/sly/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "/tmp/sly.182122"))))

This is SBCL 2.1.4.32-ef1ff011f, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
;; Slynk started at port: 38725.
SLYNK's ASDF loader finished.
38725
* WARNING: redefining SLYNK::SYMBOL-INDENTATION in DEFUN
WARNING: redefining SLYNK::MACRO-INDENTATION in DEFUN
```

**Comment by Harag** [comment] 2021-05-17 10:18
I have double checked I only have the one place where sly code exists and that is in .emacs.d/sly, (deleted all other sly extentions as well just in case) 

I have updated sbcl to what is in the latest git, I have tried with the ubuntu version of emacs 27.1 and I still get the same behaviour.

**Comment by joaotavora** [comment] 2021-05-17 10:25
> Messages buffer when message in place

Aha. Finally a clue, so when you put the message I suggested we don see that `sly` is being called twice, and concurrently.  So what happened is one sly started perfectly, the other one didn't finish starting.  That other one shouldn't even have been invoked.

How exactly do you do step 5 "open a file with `.lisp` extension" ?

**Comment by joaotavora** [comment] 2021-05-17 10:26
Never mind I've reproduced this locally.  I simply wasn't looking for this second inferior lisp buffer!

**Comment by Harag** [comment] 2021-05-17 11:15
Must I create a separate issue for you to update the documentation in 8.3 to your suggested code?

```
(add-hook 'sly-editing-mode-hook
          (lambda (); 
            (unless (sly-connected-p)
              (save-excursion (sly)))))
```

**Comment by joaotavora** [comment] 2021-05-17 11:16
> Must I create a separate issue for you to update the documentation in 8.3 to your suggested code?

No, no need.

**Comment by joaotavora** [comment] 2021-05-17 22:04
@Harag you are witnessed an unfortunate side effect of autoloading `sly.el` as the first thing that happens when you find a Lisp file.  When you do that, `sly-editing-mode` gets turned on for every buffer as a result of loading `sly.el` (this is because of a slime-detecting snippet in `sly.el`).  Then it gets turned on again as a result of finding the file.  

In the end you get two `sly` calls and the second one borks because the file is already there.  This is mostly benign, but I'll probably want to fix it anyway.

In the meantime, your snippet could become:

```
(add-hook 'sly-editing-mode-hook
          (lambda (); 
            (unless (or load-file-name (sly-connected-p))
              (save-excursion (sly)))))
```

**Comment by Harag** [comment] 2021-05-18 02:22
Thank you the new snippet works great, no more extra buffers with errors.  I am happy to close the issue there is a clean workaround, but I see you keep issues hanging around. 

What would you prefer?

**Comment by rprimus** [comment] 2021-05-18 05:57
Tue May 18 06:54:22 BST 2021

Hi @Harag ,  before closing,  can you try replacing `sly-editing-mode-hook`  in `.emacs.bare` with the following and report the results?

```lisp
(add-hook 'lisp-mode-hook
          (lambda ()
            (unless (sly-connected-p)
              (save-excursion (sly)))))
```

**Comment by joaotavora** [comment] 2021-05-18 07:01
@Harag , please don't close. There's a bug that needs solving

**Closed** 2021-06-03 14:14 UTC
Labels: bug
