### ISSUE TITLE
Hanging/crashing REPL on interrupt from Emacs

### ISSUE THREAD

**Issue by hjudt** [joaotavora/sly#242] opened 2019-06-19 10:25 UTC
Not sure if this is intended, but I can crash sly performing this (Linux, SBCL-1.5.3):
`CL-USER> (loop for i upto 10 do (sleep 1))`
Now hit C-c C-c to interrupt and select 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {...}>
Evaluation aborted on T
`CL-USER> (/ 1 3 0)`
REPL hangs indefinitely
Hitting C-c C-c again crashes the sly-pty-x-x process:
`Process sly-pty-1-1 killed`

Of course I can use selection 2: [*ABORT] Return to SLY's top level and it does not crash, which would probably be the better solution.

However, offering to kill the mrepl-remote thread might be confusing especially for new users; wouldn't it be better to also restart the REPL thread if this happens so the user has a functional REPL again for entering the next form?

**Comment by joaotavora** [comment] 2019-06-19 12:17
> However, offering to kill the mrepl-remote thread might be confusing especially for new users; wouldn't it be better to also restart the REPL thread if this happens so the user has a functional REPL again for entering the next form?

Yes it would. This is a duplicate of an existing issue (don't know which exactly). It's not super important because if you get into the habit of using `a` to select abort restarts you won't get into this situation. It's also reasonably easy to start a new REPL manually.

**Comment by joaotavora** [comment] 2019-06-19 12:40
This is a duplicate of #122. Let's handle it there.

**Closed by joaotavora** 2019-06-19 12:40 UTC
