### ISSUE TITLE
Flaky REPL bug binds `,` to `self-insert-command`

### ISSUE THREAD

**Issue by nagy** [joaotavora/sly#462] opened 2021-07-29 12:52 UTC
I am encountering a flaky bug inside the REPL, it is not immediately reproducible. Sly sometimes seems to switch into another weird state where the `,` key is not bound to `sly-mrepl-shortcut` anymore and completion ( with company ) requires manual triggering.

Please bear with me since this sometimes can need up to 10 tries to be able to show up. I just tested it with the current sly master branch.

```sh
$ emacs --version
GNU Emacs 28.0.50
$ sbcl --version
SBCL 2.1.2.nixos
$ cd sly
sly $ emacs -Q -nw -L . -l sly-autoloads --eval '(setq inferior-lisp-program "sbcl")' -f sly
```

# Steps to reproduce
Open Emacs like above.

Then type `'()` and hit `RET` . Now type `M-p` to get the last entry again and hit `RET` again.

Now sometimes sly is in this weird state where the following seems to be the case:

 - `,` is now bound to `self-insert-command` instead of `sly-mrepl-shortcut`.
 - When using company for completions, completion dialog needs to be manually triggered with `company-complete-common` instead of showing up on automatically.

I cannot seem to reproduce it with anything that does not contain parentheses. Also the second line needs to come from going back in the REPL history by hitting `M-p`. When you type this empty list in again for the second line, I cannot get this behaviour to show up. If it does not show up for you, please restart Emacs and try again up to 10 times or so.

My `.sbclrc` is empty. Is this reproducible for you? Can I help out with this some way? If you cannot reproduce it, I can try to find a more reliable way.

## Screenshot 1 (buggy state)
I am able to insert the comma just by pressing `,`. The `sly-mrepl-shortcut` command does not show up.

![buggy](https://user-images.githubusercontent.com/692274/127494312-161a2455-6c3f-4649-8e86-922334cb2ce3.png)

## Screenshot 2 (working state)
Here, by pressing `,` the `sly-mrepl-shortcut` shows up.

![working](https://user-images.githubusercontent.com/692274/127494333-d452d847-c0fa-46e3-a0f7-4bcf042b891c.png)

**Comment by joaotavora** [comment] 2021-07-29 13:15
Thanks.  I think this is still fallout from the recent commit concerning identification of comment syntax.  I'll try to reproduce.  If might be easier once you have a lot of repl output, which something like `(ql:quickload :somepackage)` could produce.

**Comment by joaotavora** [comment] 2021-07-29 13:29
I can now reproduce this consistently

**Comment by joaotavora** [comment] 2021-07-29 13:30
This is a duplicate of #459 which isn't fixed.

**Comment by nagy** [comment] 2021-07-29 13:32
Okay, thank you very much. I guess you already know, but after a bit more testing the earliest commit which allowed me to reproduce this was `fa6076c8`, which is the commit about the comment syntax you talked about.

**Comment by joaotavora** [comment] 2021-07-29 13:33
OK closing and continue to handle in #459

**Closed** 2021-07-29 13:33 UTC
Labels: bug
